//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Este código-fonte foi gerado automaticamente por Microsoft.VSDesigner, Versão 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace CS_Caixa.SiteCartorio {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Cartorio1OficioSoap", Namespace="http://1oficioararuama.com.br/webservice/")]
    public partial class Cartorio1Oficio : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback AdicionarFirmasOperationCompleted;
        
        private System.Threading.SendOrPostCallback AdicionarRegistroOperationCompleted;
        
        private System.Threading.SendOrPostCallback AdicionarProtestoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ExcluirProtestoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObterTitulosCaducadosOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Cartorio1Oficio() {
            this.Url = global::CS_Caixa.Properties.Settings.Default.CS_Caixa_SiteCartorio_Cartorio1Oficio;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event AdicionarFirmasCompletedEventHandler AdicionarFirmasCompleted;
        
        /// <remarks/>
        public event AdicionarRegistroCompletedEventHandler AdicionarRegistroCompleted;
        
        /// <remarks/>
        public event AdicionarProtestoCompletedEventHandler AdicionarProtestoCompleted;
        
        /// <remarks/>
        public event ExcluirProtestoCompletedEventHandler ExcluirProtestoCompleted;
        
        /// <remarks/>
        public event ObterTitulosCaducadosCompletedEventHandler ObterTitulosCaducadosCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://1oficioararuama.com.br/webservice/AdicionarFirmas", RequestNamespace="http://1oficioararuama.com.br/webservice/", ResponseNamespace="http://1oficioararuama.com.br/webservice/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string AdicionarFirmas(ConsultaFirma firma) {
            object[] results = this.Invoke("AdicionarFirmas", new object[] {
                        firma});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void AdicionarFirmasAsync(ConsultaFirma firma) {
            this.AdicionarFirmasAsync(firma, null);
        }
        
        /// <remarks/>
        public void AdicionarFirmasAsync(ConsultaFirma firma, object userState) {
            if ((this.AdicionarFirmasOperationCompleted == null)) {
                this.AdicionarFirmasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAdicionarFirmasOperationCompleted);
            }
            this.InvokeAsync("AdicionarFirmas", new object[] {
                        firma}, this.AdicionarFirmasOperationCompleted, userState);
        }
        
        private void OnAdicionarFirmasOperationCompleted(object arg) {
            if ((this.AdicionarFirmasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AdicionarFirmasCompleted(this, new AdicionarFirmasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://1oficioararuama.com.br/webservice/AdicionarRegistro", RequestNamespace="http://1oficioararuama.com.br/webservice/", ResponseNamespace="http://1oficioararuama.com.br/webservice/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string AdicionarRegistro(ConsultaRegistro registro) {
            object[] results = this.Invoke("AdicionarRegistro", new object[] {
                        registro});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void AdicionarRegistroAsync(ConsultaRegistro registro) {
            this.AdicionarRegistroAsync(registro, null);
        }
        
        /// <remarks/>
        public void AdicionarRegistroAsync(ConsultaRegistro registro, object userState) {
            if ((this.AdicionarRegistroOperationCompleted == null)) {
                this.AdicionarRegistroOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAdicionarRegistroOperationCompleted);
            }
            this.InvokeAsync("AdicionarRegistro", new object[] {
                        registro}, this.AdicionarRegistroOperationCompleted, userState);
        }
        
        private void OnAdicionarRegistroOperationCompleted(object arg) {
            if ((this.AdicionarRegistroCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AdicionarRegistroCompleted(this, new AdicionarRegistroCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://1oficioararuama.com.br/webservice/AdicionarProtesto", RequestNamespace="http://1oficioararuama.com.br/webservice/", ResponseNamespace="http://1oficioararuama.com.br/webservice/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string AdicionarProtesto(ConsultaProtesto protesto) {
            object[] results = this.Invoke("AdicionarProtesto", new object[] {
                        protesto});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void AdicionarProtestoAsync(ConsultaProtesto protesto) {
            this.AdicionarProtestoAsync(protesto, null);
        }
        
        /// <remarks/>
        public void AdicionarProtestoAsync(ConsultaProtesto protesto, object userState) {
            if ((this.AdicionarProtestoOperationCompleted == null)) {
                this.AdicionarProtestoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAdicionarProtestoOperationCompleted);
            }
            this.InvokeAsync("AdicionarProtesto", new object[] {
                        protesto}, this.AdicionarProtestoOperationCompleted, userState);
        }
        
        private void OnAdicionarProtestoOperationCompleted(object arg) {
            if ((this.AdicionarProtestoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AdicionarProtestoCompleted(this, new AdicionarProtestoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://1oficioararuama.com.br/webservice/ExcluirProtesto", RequestNamespace="http://1oficioararuama.com.br/webservice/", ResponseNamespace="http://1oficioararuama.com.br/webservice/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ExcluirProtesto(ConsultaProtesto protesto) {
            object[] results = this.Invoke("ExcluirProtesto", new object[] {
                        protesto});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ExcluirProtestoAsync(ConsultaProtesto protesto) {
            this.ExcluirProtestoAsync(protesto, null);
        }
        
        /// <remarks/>
        public void ExcluirProtestoAsync(ConsultaProtesto protesto, object userState) {
            if ((this.ExcluirProtestoOperationCompleted == null)) {
                this.ExcluirProtestoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnExcluirProtestoOperationCompleted);
            }
            this.InvokeAsync("ExcluirProtesto", new object[] {
                        protesto}, this.ExcluirProtestoOperationCompleted, userState);
        }
        
        private void OnExcluirProtestoOperationCompleted(object arg) {
            if ((this.ExcluirProtestoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ExcluirProtestoCompleted(this, new ExcluirProtestoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://1oficioararuama.com.br/webservice/ObterTitulosCaducados", RequestNamespace="http://1oficioararuama.com.br/webservice/", ResponseNamespace="http://1oficioararuama.com.br/webservice/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ConsultaProtesto[] ObterTitulosCaducados() {
            object[] results = this.Invoke("ObterTitulosCaducados", new object[0]);
            return ((ConsultaProtesto[])(results[0]));
        }
        
        /// <remarks/>
        public void ObterTitulosCaducadosAsync() {
            this.ObterTitulosCaducadosAsync(null);
        }
        
        /// <remarks/>
        public void ObterTitulosCaducadosAsync(object userState) {
            if ((this.ObterTitulosCaducadosOperationCompleted == null)) {
                this.ObterTitulosCaducadosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObterTitulosCaducadosOperationCompleted);
            }
            this.InvokeAsync("ObterTitulosCaducados", new object[0], this.ObterTitulosCaducadosOperationCompleted, userState);
        }
        
        private void OnObterTitulosCaducadosOperationCompleted(object arg) {
            if ((this.ObterTitulosCaducadosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObterTitulosCaducadosCompleted(this, new ObterTitulosCaducadosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://1oficioararuama.com.br/webservice/")]
    public partial class ConsultaFirma {
        
        private int consultaFirmaIdField;
        
        private string nomeField;
        
        private string cpfField;
        
        /// <remarks/>
        public int ConsultaFirmaId {
            get {
                return this.consultaFirmaIdField;
            }
            set {
                this.consultaFirmaIdField = value;
            }
        }
        
        /// <remarks/>
        public string Nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
            }
        }
        
        /// <remarks/>
        public string Cpf {
            get {
                return this.cpfField;
            }
            set {
                this.cpfField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://1oficioararuama.com.br/webservice/")]
    public partial class ConsultaProtesto {
        
        private int consultaProtestoIdField;
        
        private string idAtoField;
        
        private string devedorField;
        
        private string documentoDevedorField;
        
        private System.DateTime dataProtestoField;
        
        /// <remarks/>
        public int ConsultaProtestoId {
            get {
                return this.consultaProtestoIdField;
            }
            set {
                this.consultaProtestoIdField = value;
            }
        }
        
        /// <remarks/>
        public string IdAto {
            get {
                return this.idAtoField;
            }
            set {
                this.idAtoField = value;
            }
        }
        
        /// <remarks/>
        public string Devedor {
            get {
                return this.devedorField;
            }
            set {
                this.devedorField = value;
            }
        }
        
        /// <remarks/>
        public string DocumentoDevedor {
            get {
                return this.documentoDevedorField;
            }
            set {
                this.documentoDevedorField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DataProtesto {
            get {
                return this.dataProtestoField;
            }
            set {
                this.dataProtestoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://1oficioararuama.com.br/webservice/")]
    public partial class ConsultaRegistro {
        
        private int consultaRegistroIdField;
        
        private string dataEntradaField;
        
        private string dataRegistroField;
        
        private string protocoloField;
        
        private string naturezaField;
        
        private string matriculaField;
        
        private string dataModificadoField;
        
        private string situacaoField;
        
        private string exigenciaField;
        
        private string idAtoField;
        
        /// <remarks/>
        public int ConsultaRegistroId {
            get {
                return this.consultaRegistroIdField;
            }
            set {
                this.consultaRegistroIdField = value;
            }
        }
        
        /// <remarks/>
        public string DataEntrada {
            get {
                return this.dataEntradaField;
            }
            set {
                this.dataEntradaField = value;
            }
        }
        
        /// <remarks/>
        public string DataRegistro {
            get {
                return this.dataRegistroField;
            }
            set {
                this.dataRegistroField = value;
            }
        }
        
        /// <remarks/>
        public string Protocolo {
            get {
                return this.protocoloField;
            }
            set {
                this.protocoloField = value;
            }
        }
        
        /// <remarks/>
        public string Natureza {
            get {
                return this.naturezaField;
            }
            set {
                this.naturezaField = value;
            }
        }
        
        /// <remarks/>
        public string Matricula {
            get {
                return this.matriculaField;
            }
            set {
                this.matriculaField = value;
            }
        }
        
        /// <remarks/>
        public string DataModificado {
            get {
                return this.dataModificadoField;
            }
            set {
                this.dataModificadoField = value;
            }
        }
        
        /// <remarks/>
        public string Situacao {
            get {
                return this.situacaoField;
            }
            set {
                this.situacaoField = value;
            }
        }
        
        /// <remarks/>
        public string Exigencia {
            get {
                return this.exigenciaField;
            }
            set {
                this.exigenciaField = value;
            }
        }
        
        /// <remarks/>
        public string IdAto {
            get {
                return this.idAtoField;
            }
            set {
                this.idAtoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void AdicionarFirmasCompletedEventHandler(object sender, AdicionarFirmasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AdicionarFirmasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AdicionarFirmasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void AdicionarRegistroCompletedEventHandler(object sender, AdicionarRegistroCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AdicionarRegistroCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AdicionarRegistroCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void AdicionarProtestoCompletedEventHandler(object sender, AdicionarProtestoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AdicionarProtestoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AdicionarProtestoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void ExcluirProtestoCompletedEventHandler(object sender, ExcluirProtestoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ExcluirProtestoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ExcluirProtestoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void ObterTitulosCaducadosCompletedEventHandler(object sender, ObterTitulosCaducadosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObterTitulosCaducadosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObterTitulosCaducadosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ConsultaProtesto[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ConsultaProtesto[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591