//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CS_Caixa.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute(@"User=SYSDBA;Password=masterkey;Database=Servidor:C:\Cartorio\Total\Gerencial\BDGERENCIAL.FDB;DataSource=SERVIDOR;
Port=3050;Dialect=3;Charset=NONE;Role=RoleName;Connection lifetime=15;Pooling=true;
MinPoolSize=0;MaxPoolSize=50;Packet Size=8192;ServerType=0;Port=3050;Dialect=3;Charset=NONE;Role=RoleName;Connection lifetime=15;Pooling=true;
MinPoolSize=0;MaxPoolSize=50;Packet Size=8192;ServerType=0;")]
        public string SettingBalcao {
            get {
                return ((string)(this["SettingBalcao"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute(@"User=SYSDBA;Password=masterkey;Database=Servidor:C:\Cartorio\Total\Protesto\BANCO\BANCO_PROTESTO.FDB;DataSource=SERVIDOR;
Port=3050;Dialect=3;Charset=NONE;Role=RoleName;Connection lifetime=15;Pooling=true;
MinPoolSize=0;MaxPoolSize=50;Packet Size=8192;ServerType=0;Port=3050;Dialect=3;Charset=NONE;Role=RoleName;Connection lifetime=15;Pooling=true;
MinPoolSize=0;MaxPoolSize=50;Packet Size=8192;ServerType=0;")]
        public string SettingProtesto {
            get {
                return ((string)(this["SettingProtesto"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute(@"User=SYSDBA;Password=masterkey;Database=Servidor:C:\Cartorio\TOTAL\Central\TOTAL_CENTRAL.FDB;DataSource=SERVIDOR;
Port=3050;Dialect=3;Charset=NONE;Role=RoleName;Connection lifetime=15;Pooling=true;
MinPoolSize=0;MaxPoolSize=50;Packet Size=8192;ServerType=0;Port=3050;Dialect=3;Charset=NONE;Role=RoleName;Connection lifetime=15;Pooling=true;
MinPoolSize=0;MaxPoolSize=50;Packet Size=8192;ServerType=0;")]
        public string SettingCentral {
            get {
                return ((string)(this["SettingCentral"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute(@"User=SYSDBA;Password=masterkey;Database=Servidor:C:\Cartorio\Total\firmas\TOTAL_ASSINA.FDB;DataSource=SERVIDOR;
Port=3050;Dialect=3;Charset=NONE;Role=RoleName;Connection lifetime=15;Pooling=true;
MinPoolSize=0;MaxPoolSize=50;Packet Size=8192;ServerType=0;Port=3050;Dialect=3;Charset=NONE;Role=RoleName;Connection lifetime=15;Pooling=true;
MinPoolSize=0;MaxPoolSize=50;Packet Size=8192;ServerType=0;")]
        public string SettingBalcaoSite {
            get {
                return ((string)(this["SettingBalcaoSite"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute(@"User=SYSDBA;Password=masterkey;Database=Servidor:C:\Cartorio\Total\Notas\NOTAS.GDB;DataSource=SERVIDOR;
Port=3050;Dialect=3;Charset=NONE;Role=RoleName;Connection lifetime=15;Pooling=true;
MinPoolSize=0;MaxPoolSize=50;Packet Size=8192;ServerType=0;Port=3050;Dialect=3;Charset=NONE;Role=RoleName;Connection lifetime=15;Pooling=true;
MinPoolSize=0;MaxPoolSize=50;Packet Size=8192;ServerType=0;")]
        public string SettingNotas {
            get {
                return ((string)(this["SettingNotas"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.254.1/cartorio1oficio/WebService/Cartorio1Oficio.asmx")]
        public string CS_Caixa_SiteCartorio_Cartorio1Oficio {
            get {
                return ((string)(this["CS_Caixa_SiteCartorio_Cartorio1Oficio"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=Servidor;Initial Catalog=CS_CAIXA_DB;Persist Security Info=True;User " +
            "ID=sa;Password=P@$$w0rd")]
        public string CS_CAIXA_DBConnectionString {
            get {
                return ((string)(this["CS_CAIXA_DBConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute(@"User=SYSDBA;Password=masterkey;Database=Servidor:C:\Cartorio\TOTAL\RGI\Banco\BANCO_RGI.FDB;DataSource=SERVIDOR;
Port=3050;Dialect=3;Charset=NONE;Role=RoleName;Connection lifetime=15;Pooling=true;
MinPoolSize=0;MaxPoolSize=50;Packet Size=8192;ServerType=0;Port=3050;Dialect=3;Charset=NONE;Role=RoleName;Connection lifetime=15;Pooling=true;
MinPoolSize=0;MaxPoolSize=50;Packet Size=8192;ServerType=0;")]
        public string SettingRgi {
            get {
                return ((string)(this["SettingRgi"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute(@"User=SYSDBA;Password=masterkey;Database=Servidor:C:\Cartorio\TOTAL\ReciboNovo\BDRECIBO.FDB;DataSource=SERVIDOR;
Port=3050;Dialect=3;Charset=NONE;Role=RoleName;Connection lifetime=15;Pooling=true;
MinPoolSize=0;MaxPoolSize=50;Packet Size=8192;ServerType=0;Port=3050;Dialect=3;Charset=NONE;Role=RoleName;Connection lifetime=15;Pooling=true;
MinPoolSize=0;MaxPoolSize=50;Packet Size=8192;ServerType=0;")]
        public string SettingReciboRgi {
            get {
                return ((string)(this["SettingReciboRgi"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute(@"User=SYSDBA;Password=masterkey;Database=Servidor:C:\Cartorio\TOTAL\Recibo_Notas\BDRECIBO.FDB;DataSource=SERVIDOR;
Port=3050;Dialect=3;Charset=NONE;Role=RoleName;Connection lifetime=15;Pooling=true;
MinPoolSize=0;MaxPoolSize=50;Packet Size=8192;ServerType=0;Port=3050;Dialect=3;Charset=NONE;Role=RoleName;Connection lifetime=15;Pooling=true;
MinPoolSize=0;MaxPoolSize=50;Packet Size=8192;ServerType=0;")]
        public string SettingReciboNotas {
            get {
                return ((string)(this["SettingReciboNotas"]));
            }
        }
    }
}
