//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CS_Caixa.ObterToken {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetTokenResponse", Namespace="http://schemas.datacontract.org/2004/07/WSOficioRJ")]
    [System.SerializableAttribute()]
    public partial class GetTokenResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoErroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErroDescricaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RetornoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] TokensField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodigoErro {
            get {
                return this.CodigoErroField;
            }
            set {
                if ((this.CodigoErroField.Equals(value) != true)) {
                    this.CodigoErroField = value;
                    this.RaisePropertyChanged("CodigoErro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErroDescricao {
            get {
                return this.ErroDescricaoField;
            }
            set {
                if ((object.ReferenceEquals(this.ErroDescricaoField, value) != true)) {
                    this.ErroDescricaoField = value;
                    this.RaisePropertyChanged("ErroDescricao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Retorno {
            get {
                return this.RetornoField;
            }
            set {
                if ((object.ReferenceEquals(this.RetornoField, value) != true)) {
                    this.RetornoField = value;
                    this.RaisePropertyChanged("Retorno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Tokens {
            get {
                return this.TokensField;
            }
            set {
                if ((object.ReferenceEquals(this.TokensField, value) != true)) {
                    this.TokensField = value;
                    this.RaisePropertyChanged("Tokens");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ObterToken.IToken")]
    public interface IToken {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IToken/GetToken", ReplyAction="http://tempuri.org/IToken/GetTokenResponse")]
        CS_Caixa.ObterToken.GetTokenResponse GetToken(string CNS);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITokenChannel : CS_Caixa.ObterToken.IToken, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TokenClient : System.ServiceModel.ClientBase<CS_Caixa.ObterToken.IToken>, CS_Caixa.ObterToken.IToken {
        
        public TokenClient() {
        }
        
        public TokenClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TokenClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TokenClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TokenClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CS_Caixa.ObterToken.GetTokenResponse GetToken(string CNS) {
            return base.Channel.GetToken(CNS);
        }
    }
}
