//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CS_Caixa.DbLight {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ListArquivosXMLBDLRequest", Namespace="http://schemas.datacontract.org/2004/07/WSOficioRJ")]
    [System.SerializableAttribute()]
    public partial class ListArquivosXMLBDLRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DataFinalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DataInicialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HashField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaxRowPerPageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PageNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DataFinal {
            get {
                return this.DataFinalField;
            }
            set {
                if ((object.ReferenceEquals(this.DataFinalField, value) != true)) {
                    this.DataFinalField = value;
                    this.RaisePropertyChanged("DataFinal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DataInicial {
            get {
                return this.DataInicialField;
            }
            set {
                if ((object.ReferenceEquals(this.DataInicialField, value) != true)) {
                    this.DataInicialField = value;
                    this.RaisePropertyChanged("DataInicial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Hash {
            get {
                return this.HashField;
            }
            set {
                if ((object.ReferenceEquals(this.HashField, value) != true)) {
                    this.HashField = value;
                    this.RaisePropertyChanged("Hash");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaxRowPerPage {
            get {
                return this.MaxRowPerPageField;
            }
            set {
                if ((this.MaxRowPerPageField.Equals(value) != true)) {
                    this.MaxRowPerPageField = value;
                    this.RaisePropertyChanged("MaxRowPerPage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PageNumber {
            get {
                return this.PageNumberField;
            }
            set {
                if ((this.PageNumberField.Equals(value) != true)) {
                    this.PageNumberField = value;
                    this.RaisePropertyChanged("PageNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ListArquivosXMLBDLResponse", Namespace="http://schemas.datacontract.org/2004/07/WSOficioRJ")]
    [System.SerializableAttribute()]
    public partial class ListArquivosXMLBDLResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CS_Caixa.DbLight.ArquivoXMLBDL[] ArquivosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoErroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErroDescricaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QtdePaginasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QtdeRegistrosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RetornoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CS_Caixa.DbLight.ArquivoXMLBDL[] Arquivos {
            get {
                return this.ArquivosField;
            }
            set {
                if ((object.ReferenceEquals(this.ArquivosField, value) != true)) {
                    this.ArquivosField = value;
                    this.RaisePropertyChanged("Arquivos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodigoErro {
            get {
                return this.CodigoErroField;
            }
            set {
                if ((this.CodigoErroField.Equals(value) != true)) {
                    this.CodigoErroField = value;
                    this.RaisePropertyChanged("CodigoErro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErroDescricao {
            get {
                return this.ErroDescricaoField;
            }
            set {
                if ((object.ReferenceEquals(this.ErroDescricaoField, value) != true)) {
                    this.ErroDescricaoField = value;
                    this.RaisePropertyChanged("ErroDescricao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int QtdePaginas {
            get {
                return this.QtdePaginasField;
            }
            set {
                if ((this.QtdePaginasField.Equals(value) != true)) {
                    this.QtdePaginasField = value;
                    this.RaisePropertyChanged("QtdePaginas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int QtdeRegistros {
            get {
                return this.QtdeRegistrosField;
            }
            set {
                if ((this.QtdeRegistrosField.Equals(value) != true)) {
                    this.QtdeRegistrosField = value;
                    this.RaisePropertyChanged("QtdeRegistros");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Retorno {
            get {
                return this.RetornoField;
            }
            set {
                if ((object.ReferenceEquals(this.RetornoField, value) != true)) {
                    this.RetornoField = value;
                    this.RaisePropertyChanged("Retorno");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ArquivoXMLBDL", Namespace="http://schemas.datacontract.org/2004/07/WSOficioRJ")]
    [System.SerializableAttribute()]
    public partial class ArquivoXMLBDL : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CNSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DataImportacaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDArquivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QtdeInvalidosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QtdeRegistrosField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CNS {
            get {
                return this.CNSField;
            }
            set {
                if ((object.ReferenceEquals(this.CNSField, value) != true)) {
                    this.CNSField = value;
                    this.RaisePropertyChanged("CNS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DataImportacao {
            get {
                return this.DataImportacaoField;
            }
            set {
                if ((object.ReferenceEquals(this.DataImportacaoField, value) != true)) {
                    this.DataImportacaoField = value;
                    this.RaisePropertyChanged("DataImportacao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDArquivo {
            get {
                return this.IDArquivoField;
            }
            set {
                if ((this.IDArquivoField.Equals(value) != true)) {
                    this.IDArquivoField = value;
                    this.RaisePropertyChanged("IDArquivo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDStatus {
            get {
                return this.IDStatusField;
            }
            set {
                if ((this.IDStatusField.Equals(value) != true)) {
                    this.IDStatusField = value;
                    this.RaisePropertyChanged("IDStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int QtdeInvalidos {
            get {
                return this.QtdeInvalidosField;
            }
            set {
                if ((this.QtdeInvalidosField.Equals(value) != true)) {
                    this.QtdeInvalidosField = value;
                    this.RaisePropertyChanged("QtdeInvalidos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int QtdeRegistros {
            get {
                return this.QtdeRegistrosField;
            }
            set {
                if ((this.QtdeRegistrosField.Equals(value) != true)) {
                    this.QtdeRegistrosField = value;
                    this.RaisePropertyChanged("QtdeRegistros");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetArquivoXMLBDLRequest", Namespace="http://schemas.datacontract.org/2004/07/WSOficioRJ")]
    [System.SerializableAttribute()]
    public partial class GetArquivoXMLBDLRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HashField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDArquivoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Hash {
            get {
                return this.HashField;
            }
            set {
                if ((object.ReferenceEquals(this.HashField, value) != true)) {
                    this.HashField = value;
                    this.RaisePropertyChanged("Hash");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDArquivo {
            get {
                return this.IDArquivoField;
            }
            set {
                if ((this.IDArquivoField.Equals(value) != true)) {
                    this.IDArquivoField = value;
                    this.RaisePropertyChanged("IDArquivo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetArquivoXMLBDLResponse", Namespace="http://schemas.datacontract.org/2004/07/WSOficioRJ")]
    [System.SerializableAttribute()]
    public partial class GetArquivoXMLBDLResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoErroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DataImportacaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErroDescricaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrosImportacaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CS_Caixa.DbLight.Invalido[] InvalidosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QtdeInvalidosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QtdeRegistrosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RetornoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string URLArquivoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodigoErro {
            get {
                return this.CodigoErroField;
            }
            set {
                if ((this.CodigoErroField.Equals(value) != true)) {
                    this.CodigoErroField = value;
                    this.RaisePropertyChanged("CodigoErro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DataImportacao {
            get {
                return this.DataImportacaoField;
            }
            set {
                if ((object.ReferenceEquals(this.DataImportacaoField, value) != true)) {
                    this.DataImportacaoField = value;
                    this.RaisePropertyChanged("DataImportacao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErroDescricao {
            get {
                return this.ErroDescricaoField;
            }
            set {
                if ((object.ReferenceEquals(this.ErroDescricaoField, value) != true)) {
                    this.ErroDescricaoField = value;
                    this.RaisePropertyChanged("ErroDescricao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrosImportacao {
            get {
                return this.ErrosImportacaoField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrosImportacaoField, value) != true)) {
                    this.ErrosImportacaoField = value;
                    this.RaisePropertyChanged("ErrosImportacao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDStatus {
            get {
                return this.IDStatusField;
            }
            set {
                if ((this.IDStatusField.Equals(value) != true)) {
                    this.IDStatusField = value;
                    this.RaisePropertyChanged("IDStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CS_Caixa.DbLight.Invalido[] Invalidos {
            get {
                return this.InvalidosField;
            }
            set {
                if ((object.ReferenceEquals(this.InvalidosField, value) != true)) {
                    this.InvalidosField = value;
                    this.RaisePropertyChanged("Invalidos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int QtdeInvalidos {
            get {
                return this.QtdeInvalidosField;
            }
            set {
                if ((this.QtdeInvalidosField.Equals(value) != true)) {
                    this.QtdeInvalidosField = value;
                    this.RaisePropertyChanged("QtdeInvalidos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int QtdeRegistros {
            get {
                return this.QtdeRegistrosField;
            }
            set {
                if ((this.QtdeRegistrosField.Equals(value) != true)) {
                    this.QtdeRegistrosField = value;
                    this.RaisePropertyChanged("QtdeRegistros");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Retorno {
            get {
                return this.RetornoField;
            }
            set {
                if ((object.ReferenceEquals(this.RetornoField, value) != true)) {
                    this.RetornoField = value;
                    this.RaisePropertyChanged("Retorno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string URLArquivo {
            get {
                return this.URLArquivoField;
            }
            set {
                if ((object.ReferenceEquals(this.URLArquivoField, value) != true)) {
                    this.URLArquivoField = value;
                    this.RaisePropertyChanged("URLArquivo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Invalido", Namespace="http://schemas.datacontract.org/2004/07/WSOficioRJ")]
    [System.SerializableAttribute()]
    public partial class Invalido : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CPFCNPJField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NMatriculaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeRazaoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CPFCNPJ {
            get {
                return this.CPFCNPJField;
            }
            set {
                if ((object.ReferenceEquals(this.CPFCNPJField, value) != true)) {
                    this.CPFCNPJField = value;
                    this.RaisePropertyChanged("CPFCNPJ");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NMatricula {
            get {
                return this.NMatriculaField;
            }
            set {
                if ((object.ReferenceEquals(this.NMatriculaField, value) != true)) {
                    this.NMatriculaField = value;
                    this.RaisePropertyChanged("NMatricula");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomeRazao {
            get {
                return this.NomeRazaoField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeRazaoField, value) != true)) {
                    this.NomeRazaoField = value;
                    this.RaisePropertyChanged("NomeRazao");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ImportarArquivoBDLRequest", Namespace="http://schemas.datacontract.org/2004/07/WSOficioRJ")]
    [System.SerializableAttribute()]
    public partial class ImportarArquivoBDLRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] ArquivosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HashField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Arquivos {
            get {
                return this.ArquivosField;
            }
            set {
                if ((object.ReferenceEquals(this.ArquivosField, value) != true)) {
                    this.ArquivosField = value;
                    this.RaisePropertyChanged("Arquivos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Hash {
            get {
                return this.HashField;
            }
            set {
                if ((object.ReferenceEquals(this.HashField, value) != true)) {
                    this.HashField = value;
                    this.RaisePropertyChanged("Hash");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BDLightResponse", Namespace="http://schemas.datacontract.org/2004/07/WSOficioRJ")]
    [System.SerializableAttribute()]
    public partial class BDLightResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoErroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErroDescricaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RetornoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodigoErro {
            get {
                return this.CodigoErroField;
            }
            set {
                if ((this.CodigoErroField.Equals(value) != true)) {
                    this.CodigoErroField = value;
                    this.RaisePropertyChanged("CodigoErro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErroDescricao {
            get {
                return this.ErroDescricaoField;
            }
            set {
                if ((object.ReferenceEquals(this.ErroDescricaoField, value) != true)) {
                    this.ErroDescricaoField = value;
                    this.RaisePropertyChanged("ErroDescricao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Retorno {
            get {
                return this.RetornoField;
            }
            set {
                if ((object.ReferenceEquals(this.RetornoField, value) != true)) {
                    this.RetornoField = value;
                    this.RaisePropertyChanged("Retorno");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DbLight.Ibdlight")]
    public interface Ibdlight {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ibdlight/ListArquivosXMLBDL", ReplyAction="http://tempuri.org/Ibdlight/ListArquivosXMLBDLResponse")]
        CS_Caixa.DbLight.ListArquivosXMLBDLResponse ListArquivosXMLBDL(CS_Caixa.DbLight.ListArquivosXMLBDLRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ibdlight/GetArquivoXMLBDL", ReplyAction="http://tempuri.org/Ibdlight/GetArquivoXMLBDLResponse")]
        CS_Caixa.DbLight.GetArquivoXMLBDLResponse GetArquivoXMLBDL(CS_Caixa.DbLight.GetArquivoXMLBDLRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ibdlight/ImportarArquivoBDL", ReplyAction="http://tempuri.org/Ibdlight/ImportarArquivoBDLResponse")]
        CS_Caixa.DbLight.BDLightResponse ImportarArquivoBDL(CS_Caixa.DbLight.ImportarArquivoBDLRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ibdlight/SetBDLightAtualizado", ReplyAction="http://tempuri.org/Ibdlight/SetBDLightAtualizadoResponse")]
        CS_Caixa.DbLight.BDLightResponse SetBDLightAtualizado(string Hash);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IbdlightChannel : CS_Caixa.DbLight.Ibdlight, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IbdlightClient : System.ServiceModel.ClientBase<CS_Caixa.DbLight.Ibdlight>, CS_Caixa.DbLight.Ibdlight {
        
        public IbdlightClient() {
        }
        
        public IbdlightClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IbdlightClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IbdlightClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IbdlightClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CS_Caixa.DbLight.ListArquivosXMLBDLResponse ListArquivosXMLBDL(CS_Caixa.DbLight.ListArquivosXMLBDLRequest request) {
            return base.Channel.ListArquivosXMLBDL(request);
        }
        
        public CS_Caixa.DbLight.GetArquivoXMLBDLResponse GetArquivoXMLBDL(CS_Caixa.DbLight.GetArquivoXMLBDLRequest request) {
            return base.Channel.GetArquivoXMLBDL(request);
        }
        
        public CS_Caixa.DbLight.BDLightResponse ImportarArquivoBDL(CS_Caixa.DbLight.ImportarArquivoBDLRequest request) {
            return base.Channel.ImportarArquivoBDL(request);
        }
        
        public CS_Caixa.DbLight.BDLightResponse SetBDLightAtualizado(string Hash) {
            return base.Channel.SetBDLightAtualizado(Hash);
        }
    }
}
